### ISSUE TITLE
Upload succeeds even if the receiver throws exception

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-upload-flow#145]
Vaadin 13.0.11, Firefox 68.0.1

I have a very simple multi-file Upload component, configured in a way that `Receiver.receiveUpload()` always fails (always throws an exception). However, when I try to upload the files, the Upload component shows all uploads as successful (shows a check mark along all uploaded files in the browser). Also, the upload HTTP POST request ends with 200 OK, while it should end with 500 INTERNAL SERVER ERROR.

Attaching a screenshot.
![Screenshot from 2019-08-01 16-55-35](https://user-images.githubusercontent.com/254091/62299395-8a8e3d00-b47d-11e9-932e-6d5e2c0fbbd5.png)

**Comment by mvysny** [comment]
However, the server-side log contains lots of exceptions, as it should:
```
[http-nio-8080-exec-1] ERROR com.vaadin.flow.server.DefaultErrorHandler - 
com.vaadin.flow.server.UploadException: Upload failed
	at com.vaadin.flow.server.communication.StreamReceiverHandler.streamToReceiver(StreamReceiverHandler.java:486)
	at com.vaadin.flow.server.communication.StreamReceiverHandler.handleFileUploadValidationAndData(StreamReceiverHandler.java:324)
	at com.vaadin.flow.server.communication.StreamReceiverHandler.handleStream(StreamReceiverHandler.java:253)
	at com.vaadin.flow.server.communication.StreamReceiverHandler.handleMultipartFileUploadFromInputStream(StreamReceiverHandler.java:226)
	at com.vaadin.flow.server.communication.StreamReceiverHandler.doHandleMultipartFileUpload(StreamReceiverHandler.java:177)
	at com.vaadin.flow.server.communication.StreamReceiverHandler.handleRequest(StreamReceiverHandler.java:135)
	at com.vaadin.flow.server.communication.StreamRequestHandler.handleRequest(StreamRequestHandler.java:96)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1507)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:242)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Foo
	at com.vaadin.starter.skeleton.MainView$1.receiveUpload(MainView.java:26)
	at com.vaadin.flow.component.upload.Upload$DefaultStreamVariable.getOutputStream(Upload.java:592)
	at com.vaadin.flow.server.communication.StreamReceiverHandler.streamToReceiver(StreamReceiverHandler.java:415)
	... 31 more
```

**Comment by mvysny** [comment]
[example-project.zip](https://github.com/vaadin/vaadin-upload-flow/files/3457061/example-project.zip)

**Comment by denis-anisimov** [comment]
The example is a bit artificial since the exception is thrown in the `OutputStream` getter.
Normally the exception is thrown on write/read.
So more proper example is :
```
Upload upload = new Upload(new Receiver() {
            @Override
            public OutputStream receiveUpload(String fileName,
                    String mimeType) {
                return new OutputStream() {

                    @Override
                    public void write(int b) throws IOException {
                        throw new RuntimeException("Foo");
                    }
                };
            }
        });
```

Here the exception is thrown during write into the `OutputStream`  instance.
That what may happen during a file upload.
And the issue is the same: the server side doesn't notify the client side anyhow.

**Comment by denis-anisimov** [comment]
It looks like server side doesn't affect the client side anyhow in any situation.
At the moment the only way to fail upload is some logic in the client side which may decide that something goes wrong.
There is no code on the server side which somehow notify the client side that upload has failed.

So we need either API on the client side which allows to notify an upload error or the client side should somehow fail itself in a better way. E.g. when the stream is closed prematurely: the number of written bytes is less than the file size....
I'm not sure wether it's possible though.
We need help from components team...

**Comment by denis-anisimov** [comment]
Made a ticket on the client side web component repo: https://github.com/vaadin/vaadin-upload/issues/309

**Comment by denis-anisimov** [comment]
As it's mentioned in the original description the response status is always 200. But it should return 500 in case of server side exception.
In that case the client side shows an error.
