### ISSUE TITLE
[Spring] When enabling @EnableWebMvc the upload fails due to missing multipart

### ISSUE THREAD

**Issue by AlexRoig** [vaadin/vaadin-upload-flow#59]
Spring Boot: 2.0.2RELEASE
Flow: RC5

On a project that I'm working, I needed to upload files and later on provide a URL to download them. I did it very simple, upload to a folder and register a resource handler for static file serving from filesystem.

Whenever I enable the WebMvc, the multipart configuration goes away and the upload component throws an exception indicating the missing multipart configuration.
If I add a bean like this, then the exception is not thrown but the file is not uploaded at all nether any of the events is triggered:

```
@Bean(name = "multipartResolver")
public CommonsMultipartResolver multipartResolver() {
        CommonsMultipartResolver multipartResolver = new CommonsMultipartResolver();
        multipartResolver.setMaxUploadSize(-1);
        return multipartResolver;
}
```
In order to provide a workaround, I removed the `@EnableWebMvc` and created a `@RestController` with `@GetMapping("/static/**") public ResponseEntity<Resource> serve(HttpServletRequest request){`

I think that this will be a typical use-case and should either be fixed or document it properly the multipart configuration.

**Comment by denis-anisimov** [comment]
Hi,
thank you for reporting the issue but I'm confused with the description.
First of all: you mention that you are uploading files. How do you upload them? 
Do you use `Upload`  component for that?

The next thing: `@EnableWebMvc` which you are referring to is not Vaadin annotation.
So it looks like the behavior which you describe is not Vaadin behavior but rather Spring behavior.

And if I got it right then the issue is a pure Spring issue: when `@EnableWebMvc` is used then the multipart configuration goes away. And the only relation of this ticket to Vaadin is using `Upload`  component which throws an exception because of lacking multipart configuration.

If my understanding is correct then I would say this is a bug in Spring.
We can't do anything to fix this on our side. 
As you mentioned the only possible solution is to mention that in the docs.
And the question is: where. I don't see any appropriate place for this. And it won't be discoverable I think anyway. So it will be tricky to find it.

It looks like the most proper way is to create a ticket for Spring about that.

**Comment by heruan** [comment]
@denis-anisimov I'm experiencing a similar issue, see https://github.com/vaadin/spring/issues/299

It does not happen only with `@EnableWebMvc` but also with other `@Enable*` Spring annotations, e.g. OAuth2 `@EnableAuthorizationServer` or `@EnableResourceServer`.

I don't know exactly why the multipart config failing here, but couldn't this also be related to the use of the dispatcher discussed in https://github.com/vaadin/spring/issues/331?

**Comment by denis-anisimov** [comment]
Alright, thanks to let us know.
Needs investigation.

**Comment by denis-anisimov** [comment]
I cannot reproduce it at least with `@EnableAuthorizationServer` and `@EnableWebSecurity`.
Will see what happens with other annotations.

**Comment by heruan** [comment]
Me neither with the latest versions, but I noticed that now with `@EnableAuthorizationServer` OAuth2 endpoints won't work: requests to e.g. `/oauth/token` gets a Vaadin HTML response 😕

**Comment by denis-anisimov** [comment]
Confirmed : there is an exception when `@EnableWebMvc` is used.

```
java.lang.IllegalStateException: Unable to process parts as no multi-part configuration has been provided
	at org.apache.catalina.connector.Request.parseParts(Request.java:2826) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.connector.Request.getParts(Request.java:2793) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.connector.RequestFacade.getParts(RequestFacade.java:1084) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:375) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:93) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.<init>(StandardMultipartHttpServletRequest.java:86) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.multipart.support.StandardServletMultipartResolver.resolveMultipart(StandardServletMultipartResolver.java:93) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.checkMultipart(DispatcherServlet.java:1128) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
```

**Comment by denis-anisimov** [comment]
I would say that the behavior in the ticket is expected.
There is no default `MultipartResolver`. 
See https://www.logicbig.com/tutorials/spring-framework/spring-web-mvc/multipart-resolver.html.
You should choose which mutlipart resolver you want to use and make it available via configuration.

But then there is a question : why does it work without `@EnableMvc`. 
That's something which I don't understand and trying to debug....

There is some difference between spring boot app without `@EnableMvc` and with it.

**Comment by heruan** [comment]
Plus, I'm not using `@EnableWebMvc` and still I'm getting the exception. Maybe a race condition during context bootstrap, when multiple servlets are mapped by different starters?

**Comment by denis-anisimov** [comment]
There is a possibility that I won't be able to find a reason for this behavior.
Spring is Spring and this is its normal behavior: total magic without any way to understand why it behaves in this way.
I'm trying to debug but it's extremely hard since it's Spring.
And every time when I'm doing this I permanently interrupted by some other support activity.
So it's nearly impossible to work on this ticket being on support.

**Comment by heruan** [comment]
Any chance @snicoll can give us a hint about this? It seems somewhat related to https://github.com/vaadin/spring/issues/331

**Comment by denis-anisimov** [comment]
I don't think it's related.

The main question for now : why does it work at all by default in Spring boot if there is no `@EnableWebMvc`annotation (or something other).
It looks like the behavior in the ticket is the correct one.
But it works without explicitly defined `MultipartResolver` in the simplest case.
And this is the question: why?

**Comment by denis-anisimov** [comment]
Some current investigation results to save until I interrupted again:
Tomcat  `org.apache.catalina.connector.Request` class has methods `parseParameters` and `getParts`.

The first method is called by the `getParameter(String)`   method (from `RequestFacade`).

Both methods calls `parseParts` but with different parameter value.
In the first case the parameter value prevents throwing an exception and sets internal `parts`  field to an empty list.

In the second case parameter value thrown an exception (the conditions are the same).

If there is no `@EnableMvc` annotation then the `getParameter` method  is called and sets the `parts` field.

Then the `getParts` method is called and it calls `parseParts`  again but since `parts`  are already initialized then it just exits.

When `@EnableMvc` is used then there is no preliminary `getParameter(String)` method call and when `getParts` is called the `parts` is null which causes further logic execution and an exception is thrown.

So the difference is in the `getParameter` method call.
The latter method is called from `HiddenHttpMethodFilter`.
The latter filter is not called at all if there is no `@EnableMvc`.
It looks like this is the reason.
Now it remains to understand what the `HiddenHttpMethodFilter` is and why it's not called in another case.

**Comment by denis-anisimov** [comment]
`javax.servlet.annotation.MultipartConfig` instance in both cases is `null`

**Comment by denis-anisimov** [comment]
In reality there is a sublcass org.springframework.boot.web.servlet.filter.OrderedHiddenHttpMethodFilter of the `HiddenHttpMethodFilter`. It's involved in the filters chain.

**Comment by denis-anisimov** [comment]
.`org.apache.catalina.core.ApplicationFilterChain` which is `javax.servlet.FilterChain`
contains `org.springframework.boot.web.servlet.filter.OrderedHiddenHttpMethodFilter` which is declared in the Spring boot autoconfiguration `WebMvcAutoConfiguration` class via 

```
@Bean
	@ConditionalOnMissingBean(HttpPutFormContentFilter.class)
	@ConditionalOnProperty(prefix = "spring.mvc.formcontent.putfilter", name = "enabled", matchIfMissing = true)
	public OrderedHttpPutFormContentFilter httpPutFormContentFilter() {
		return new OrderedHttpPutFormContentFilter();
	}
```

when there is no `@EnableWebMvc` annotation.

With `@EnableWebMvc` annotation the filter chain doesn't contain `org.springframework.boot.web.servlet.filter.OrderedHiddenHttpMethodFilter` at all.

I don't know why it happens but that's the reason of absence the exception without `@EnableWebMvc` annotation.

Normally the exception should be thrown. It tells that the developer should provide `MultipartResolver` bean in the configuration.
I would consider default behavior of Spring boot as a bug.

I will close this ticket and create a ticket in the docs repository to document `Upload` behavior with Spring.

Thank you all for reporting and participation in this issue.

**Comment by denis-anisimov** [comment]
Ticket in the documentation : https://github.com/vaadin/flow-and-components-documentation/issues/240

**Comment by heruan** [comment]
The documentation says to provide a `MultipartResolver` bean, but as reporter by the OP and also by me in https://github.com/vaadin/spring/issues/299 exposing the bean just makes the exception disappear but no events from the `Upload` component are triggered.

Has the solution provided in the documentation been tested?

**Comment by heruan** [comment]
@AlexRoig did you solve the issue? If not, I think this should be reopened.

**Comment by heruan** [comment]
@denis-anisimov I'm still not able to upload files even following the new documentation. Have you been able to test it? Beware that the upload *seems* to succeed but no data is received nor the event listeners fire.

**Comment by denis-anisimov** [comment]
Yes, of course it has been tested.
But it's true that now it doesn't work.

Here is the code which I've used to test :

```
@Route("multipart-upload")
public class UploadView extends Div {

    public UploadView() {
        MultiFileMemoryBuffer buffer = new MultiFileMemoryBuffer();
        Upload upload = new Upload(buffer);

        upload.addSucceededListener(event -> {
            Component component = createComponent(event.getMIMEType(),
                    event.getFileName(),
                    buffer.getInputStream(event.getFileName()));
            add(component);
        });

        add(upload);
    }

    private Component createComponent(String mimeType, String fileName,
            InputStream stream) {
        if (!mimeType.startsWith("text")) {
            throw new IllegalStateException();
        }
        String text = "";
        try {
            text = IOUtils.toString(stream, "UTF-8");
        } catch (IOException e) {
            text = "exception reading stream";
        }
        return new Text(text);
    }
```

Also there should be a bean in the configuration 

```
@Bean(name = "multipartResolver")
    public CommonsMultipartResolver multipartResolver() {
        return new CommonsMultipartResolver();
    }
```

The code should show the uploaded text files content.
But now once this bean is added to the configuration the succeeded listener is not called at all.

I'm not sure that this is the same issue since the original issue is about exception.
There is no any exception now but the functionality is broken. So it's kind of a different issue now.

**Comment by heruan** [comment]
Thank you @denis-anisimov for the response. Indeed the issue is still the same: the OP stated that when opening the issue

> If I add a bean like this, then the exception is not thrown but the file is not uploaded at all nether any of the events is triggered […]

and the same did I in https://github.com/vaadin/spring/issues/299#issuecomment-401526588

I really hope we can find a solution, since I couldn't go production with 10 nor with 11 due to this.

**Comment by heruan** [comment]
@denis-anisimov Any news about this?

**Comment by denis-anisimov** [comment]
No, as far as I know.
Nobody is working on it and it's not prioritized.

**Comment by denis-anisimov** [comment]
Oh, this is insane (==Spring).
Now upload doesn't work at all regardless of `@EnableWebMvc` annotation presence.

It definitely worked when I've been debugging it more than month ago.

Apparently this is a different issue than the original one: no any exception but upload just doesn't work.
But anyway upload doesn't work with Spring at all.

**Comment by heruan** [comment]
Yeah, it's frustrating. The OP reported that with `CommonsMultipartResolver` there is no exception, so I think the issue is still the same:

> If I add a bean like this, then the exception is not thrown […]

Still, it doesn't work. Thank you for diving into this once again!

**Comment by denis-anisimov** [comment]
The incoming `HttpServletRequest` is `org.springframework.web.multipart.support.StandardMultipartHttpServletRequest` and it doesn't contain any `multipartFiles`. So the request is just empty and that's the reason of the behavior.

Now it remains to understand why the request is empty.

**Comment by denis-anisimov** [comment]
Extracted to #84.

**Comment by andrea-tomassi** [comment]
Not sure you still have the problem. 
My experience (vaadin Flow 10) is that the upload is not working if you use:
```
@Bean(name = "multipartResolver")
    public CommonsMultipartResolver multipartResolver() {
        return new CommonsMultipartResolver();
    }
```
If you delete the Bean form Configuration the upload works well out of the box! Just add the component and add the listener. Stop. 
It seems that now the Bean declaration is part of the base Vaadin project, and adding your own declaration breaks the upload.

**Comment by kuoho** [comment]
`@EnableWebMvc` import `DelegatingWebMvcConfiguration`, and `DelegatingWebMvcConfiguration` extends `WebMvcConfigurationSupport`, `WebMvcAutoConfiguration`   conditionalOnMissingBean(WebMvcConfigurationSupport.class). and  the bean `OrderedHiddenHttpMethodFilter` inside  `WebMvcAutoConfiguration`. I think this maybe reason why `OrderedHiddenHttpMethodFilter` didn't init
